fileSettings:
  uploadLimitSize: 104857600
  dirSplit:
  - 5
  - 5
  - 6
intervals:
  dapp:
    reconnection: 10000
    checkConnection: 120000
    refreshInitList: 600000
  fs:
    deleteFileAfter: 86400000
dirs:
  storage: 'storage/'